{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kuber-deployer.serviceAccountName" . }}
  labels:
{{ include "kuber-deployer.labels" . | indent 4 }}
{{- end -}}
